platform :ios, '16.0'
project 'Example/Example.xcodeproj'

target 'Example' do
  if ENV['USE_STATIC_LIBRARIES'] != nil
    use_modular_headers!
  else
    use_frameworks!
  end

  pod 'SnapKit'
  pod 'Keyboard+LayoutGuide'
  pod 'Moya/Core'
  pod 'Kingfisher'
  pod 'LocalPod', :path => 'LocalPods',
                  :testspecs => ['Tests']

  target 'ExampleTests' do
    inherit! :search_paths
    pod 'AutoMate'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name.include? 'LocalPod'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      end
    end

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
