ignore:
- "Rugby.swift"
- "Sources/Rugby/Commands"
- "Sources/RugbyFoundation/Vault"
- "Sources/RugbyFoundation/Core/Warmup/Decompressor.swift"
- "Sources/RugbyFoundation/Core/Warmup/URLSession.swift"
- "Sources/RugbyFoundation/Core/Common/Shell/ShellExecuter.swift"
- "Sources/RugbyFoundation/Core/Common/ProcessMonitor/ProcessMonitor.swift"
