#!/bin/ruby

lane :cache_both do
    cocoapods(try_repo_update_on_error: true)
    sh "cd .. && rugby -s ios sim --no-bell"
    run_unit_tests
    build_ios
end

lane :cache_exclude do
    cocoapods(try_repo_update_on_error: true)
    sh "cd .. && rugby -e Alamofire --no-bell"
    run_unit_tests
end

lane :cache_different_config do
    cocoapods(try_repo_update_on_error: true)
    sh "cd .. && rugby -c \"Staging With Spaces\" --no-bell"
    build(configuration: "Staging With Spaces")
end