#!/bin/ruby

lane :focus_tests do
    focus_basic_usage
end

private_lane :focus_basic_usage do
    cocoapods(try_repo_update_on_error: true)
    Dir.chdir("..") do
        sh "rugby --no-bell -q"
        sh "rugby focus \"Pods-TestProject\" --no-bell -q"
        sh "rugby focus \"TestProject\" -p TestProject/TestProject.xcodeproj --no-bell -q"
    end
    build
end