#!/bin/ruby

lane :plans_tests do
    plans_basic_usage
end

private_lane :plans_basic_usage do
    Dir.chdir("..") do
        sh "rugby example --no-bell -q"
        sh "cat .rugby/plans.yml"
        sh "rugby --plan usual --no-bell -q"
    end
    build

    sh "cd .. && rugby rollback -q"
    ensure_git_clean
end
