lane :run_unit_tests do |options|
   scan(workspace: "TestProject.xcworkspace",
        scheme: "TestProject",
        xcargs: 'COMPILER_INDEX_STORE_ENABLE=NO SWIFT_COMPILATION_MODE=wholemodule',
        prelaunch_simulator: true,
        devices: "iPhone 11 (14.3)",
        skip_package_dependencies_resolution: true)
end

lane :build do |options|
   gym(workspace: "TestProject.xcworkspace",
       scheme: "TestProject",
       xcargs: 'COMPILER_INDEX_STORE_ENABLE=NO SWIFT_COMPILATION_MODE=wholemodule',
       skip_archive: true,
       skip_codesigning: true,
       sdk: "iphonesimulator",
       skip_package_dependencies_resolution: true)
end