#!/bin/ruby

lane :run_unit_tests do |options|
    scan(workspace: "TestProject.xcworkspace",
         scheme: "TestProject",
         xcargs: 'COMPILER_INDEX_STORE_ENABLE=NO SWIFT_COMPILATION_MODE=wholemodule',
         prelaunch_simulator: true,
         devices: "iPhone 11 (14.4)",
         skip_package_dependencies_resolution: true)
end

lane :build do |options|
    gym(workspace: "TestProject.xcworkspace",
        scheme: "TestProject",
        configuration: options[:configuration].nil? ? nil : options[:configuration],
        xcargs: 'COMPILER_INDEX_STORE_ENABLE=NO SWIFT_COMPILATION_MODE=wholemodule',
        skip_archive: true,
        skip_codesigning: true,
        sdk: "iphonesimulator",
        skip_package_dependencies_resolution: true)
end

lane :build_ios do |options|
    gym(project: "Pods/Pods.xcodeproj",
        scheme: "Pods-TestProject",
        configuration: options[:configuration].nil? ? nil : options[:configuration],
        xcargs: 'COMPILER_INDEX_STORE_ENABLE=NO SWIFT_COMPILATION_MODE=wholemodule',
        skip_archive: true,
        skip_codesigning: true,
        sdk: "iphoneos",
        skip_package_dependencies_resolution: true)
end

lane :check_that_scemes_empty do |options|
    xcschemes = '../TestProject/TestProject.xcodeproj/xcshareddata/xcschemes'
    if Dir.empty?(xcschemes) then
        UI.message("Empty schemes: OK")
    else
        files = Dir[xcschemes + "/*"].map { |p| File.basename(p) }
        UI.user_error!("Found schemes: " + files.to_s)
    end
end
