platform :ios, '11.0.1'

target 'TestProject' do
  use_frameworks!
  
  pod 'SnapKit'
  pod 'Keyboard+LayoutGuide'
  pod 'R.swift'
  pod 'LocalPod', :path => '.', :testspecs => ['Tests']

  target 'TestProjectTests' do
      inherit! :search_paths
  end

  target 'TestProjectUITests' do

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name.include? 'LocalPod'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      end
    end
  end
end
