# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
flutter_application_path = './my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterRugbyIntegration' do
  # Comment the next line if you don't want to use dynamic frameworks
  install_all_flutter_pods(flutter_application_path)

  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  # Pods for FlutterRugbyIntegration

  target 'FlutterRugbyIntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterRugbyIntegrationUITests' do
    # Pods for testing
  end

end
#
#post_install do |installer|
#  flutter_post_install(installer) if defined?(flutter_post_install)
#end
#
#post_integrate do |installer|
#  project = Xcodeproj::Project.open("FlutterRugbyIntegration.xcodeproj")
#  project.targets.each do |target|
#    script_need_to_be_removed = '[CP-User] Run Flutter Build my_flutter Script'
#
#    phase = target.shell_script_build_phases.select { |phase| phase.name.include?(script_need_to_be_removed) }.first
#    unless phase.nil?
#      target.build_phases.delete(phase)
#      puts "script #{script_need_to_be_removed} removed"
#    end
#  end
#  project.save()
#end
