name: SPM Dependencies

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1' # every monday AM 8:00
jobs:
  dependencies:
    uses: MarcoEidinger/swift-package-dependencies-check/.github/workflows/reusableWorkflow.yml@v2
    with:
      commit-message: 'Bump spm dependencies'